### ISSUE TITLE
Show changelog do not work

### ISSUE THREAD

**Issue by GregorHak** [DrOgres/twdu#57]
![Image](https://github.com/user-attachments/assets/1c85e743-4a23-4b95-8bbf-d218a4b395c1)

**Comment by DrOgres** [comment]
this should be fixed in the next update from free league

**Comment by GregorHak** [comment]
@DrOgres - like in https://github.com/DrOgres/twdu/issues/42#event-18153339241 problem still occurs
